config/routes.rb
Rails.application.routes.draw do
  post 'slackbot', to: 'slackbot#event'

  get 'logout', to: 'sessions#destroy', as: :logout
  root to: 'pages#home'

  resources :exchanges, except: [:index], path: '/' do
    resources :participants, only: [:create, :update, :destroy] do
      get 'retrieve/:login_token', to: 'sessions#create', as: :retrieve
    end
  end
end

app/models/exchange.rb
class Exchange < ApplicationRecord
  STAGES = %w(signup matched completed).freeze

  include RandomPermalink

  has_many :participants, dependent: :destroy
  has_many :participant_matches, dependent: :destroy

  before_validation :set_initial_stage

  validates :title, presence: true
  validates :match_at, presence: true, future: true, if: :match_at_changed?
  validates :exchange_at, presence: true, future: true, if: :exchange_at_changed?
  validates :stage, inclusion: { in: STAGES }

  validate :validate_match_at_date, :validate_match_at_editability, if: :match_at_changed?
  validate :validate_exchange_at_editability, if: :exchange_at_changed?

  scope :require_matching, -> { where('match_at <= ? AND stage = ?', Time.now.utc, 'signup') }
  scope :require_completing, -> { where('exchange_at <= ? AND stage = ?', Time.now.utc, 'matched') }
  scope :require_match_reminder_sending, lambda {
    where('match_at <= ? AND match_reminder_sent_at IS NULL', Time.now.utc + 7.days)
  }
  scope :require_exchange_reminder_sending, lambda {
    where('exchange_at <= ? AND exchange_reminder_sent_at IS NULL', Time.now.utc + 7.days)
  }

  def pair_participants
    matchmaker.pair.each do |gifter, giftee|
      participant_matches.build(gifter: gifter, giftee: giftee)
    end
  end

  def match!
    pair_participants
    self.stage = 'matched'
    save!

    send_match_ready_emails
  end

  def complete!
    self.stage = 'completed'
    save!
  end

  STAGES.each do |status_name|
    define_method "#{status_name}_stage?".to_sym do
      stage == status_name
    end
  end

  def send_match_reminder_emails
    send_participants_email(:match_reminder)
    touch(:match_reminder_sent_at)
  end

  def send_match_ready_emails
    send_participants_email(:match_ready)
  end

  def send_exchange_reminder_emails
    send_participants_email(:exchange_reminder)
    touch(:exchange_reminder_sent_at)
  end

  private

  def match_at_changed?
    super || time_zone_changed?
  end

  def exchange_at_changed?
    super || time_zone_changed?
  end

  def validate_match_at_date
    errors.add(:match_at, "must be before the exchange date") if (match_at && exchange_at) && (match_at >= exchange_at)
  end

  def validate_match_at_editability
    if !new_record? && (matched_stage? || completed_stage?)
      errors.add(:match_at, "cannot be altered after matching has taken place")
    end
  end

  def validate_exchange_at_editability
    if !new_record? && completed_stage?
      errors.add(:exchange_at, "cannot be altered after exchanging has taken place")
    end
  end

  def send_participants_email(email_name)
    email_name = "send_#{email_name}_email".to_sym
    participants.participating.each(&email_name)
  end

  def set_initial_stage
    self.stage ||= 'signup'
  end

  def matchmaker
    @matchmaker ||= Elfkit::Matchmaker.new(participants.participating)
  end
end

app/controllers/exchanges_controller.rb
class ExchangesController < ApplicationController
  include AdminOnlyActions

  before_action do
    @exchange = Exchange.find_by_permalink!(params[:id]) if params[:id]
  end

  before_action :admin_only, only: [:edit, :update, :destroy]

  around_action :use_exchange_timestamp

  def new
    @exchange = Exchange.new(match_at: 2.weeks.from_now, exchange_at: 4.weeks.from_now)
    @first_participant = Participant.new
  end

  def create
    @first_participant = Participant.new(safe_participant_params)
    @first_participant.admin = true

    @exchange = Exchange.new(safe_exchange_params)
    @exchange.participants << @first_participant

    if @exchange.save
      redirect_to exchange_path(@exchange, invited: @first_participant.permalink)
    else
      render :new
    end
  end

  def show
    @participants = @exchange.participants.participating

    if params[:invited]
      @participant = @exchange.participants.find_by_permalink(params[:invited])
    else
      @participant = @exchange.participants.build
    end
  end

  def edit
  end

  def update
    if @exchange.update_attributes(safe_exchange_params)
      redirect_to exchange_path(@exchange)
    else
      render :edit
    end
  end

  def destroy
    if @exchange.destroy
      redirect_to root_path, notice: "Your exchange has been cancelled and your participants notified."
    else
      redirect_to exchange_path(@exchange), alert: "Sorry, we couldn't delete your exchange. " \
        "Please try again later."
    end
  end

  private

  def use_exchange_timestamp
    Time.zone = request_time_zone
    yield
  ensure
    Time.zone = nil
  end

  def request_time_zone
    if params[:exchange] && params[:exchange][:time_zone]
      params[:exchange][:time_zone]
    elsif @exchange
      @exchange.time_zone
    end
  end

  def safe_exchange_params
    params.require(:exchange).permit(:title, :match_at, :exchange_at, :time_zone)
  end

  def safe_participant_params
    params[:exchange].require(:participant).permit(:name, :email_address)
  end
end

app/helpers/exchanges_helper.rb
module ExchangesHelper
  def countdown_timer(deadline)
    content_tag(:span, '', data: { date: deadline.to_s(:iso8601) }, class: 'js-countdown-timer')
  end

  def current_tz_info
    "#{Time.zone.name} #{Time.zone.formatted_offset}"
  end

  def datepicker_field(objectname, fieldname, selected_time)
    selected_time = selected_time.beginning_of_hour

    content_tag(:div, class: 'js-datepicker', data: { date: selected_time.to_s(:iso8601) }) do
      components = [].tap do |s|
        s << dateselect_field(fieldname, selected_time)
        s << timeselect_field(fieldname, selected_time)
        s << datepicker_hidden_fields(objectname, fieldname, selected_time)
      end

      safe_join(components, " ")
    end
  end

  def dateselect_field(fieldname, _selected_time)
    text_field_tag "#{fieldname}_date", '', placeholder: "Click to select", value: '',
      class: 'u-two-thirds-width js-datepicker--date'
  end

  def timeselect_field(fieldname, selected_time)
    options = (0..23).map { |hour| ["#{hour.to_s.rjust(2, '0')}:00", hour] }
    select_tag "#{fieldname}_time", options_for_select(options, selected_time.hour),
      class: 'u-one-third-width js-datepicker--time'
  end

  def datepicker_hidden_fields(objectname, fieldname, selected_time)
    parts = [:year, :month, :day, :hour, :min].each_with_index.map do |time_part, i|
      hidden_field_tag("#{objectname}[#{fieldname}(#{i}i)]", selected_time.send(time_part),
        class: "js-datepicker--hidden js-datepicker--#{time_part}")
    end

    safe_join(parts, " ")
  end
end

app/views/exchanges/_completed.html.haml
.row
  .ten.columns.offset-by-one
    %h2 This exhange is finished
    - if logged_in?
      %p We hope everyone had a great time, and that #{current_participant.giftee.name} enjoyed their present.
    - else
      %p We hope everyone had a great time and nobody got stiffed on a present (I'm looking at you, Bob).

app/views/exchanges/_matched.html.haml
- if logged_in?
  .row
    .six.columns
      %h2 Your giftee is:
    .six.columns
      %a.secret-box.js-secret-box{:href => '#'}
        .secret-box--contents= current_participant.giftee.name
        %span.secret-box--reveal Click to reveal match for 3s

- else
  .row
    .ten.columns.offset-by-one
      %h2 Signups are closed!
      %p
        Sorry, all of the spaces have been filled for this exchange and matches have been made.
        You need to be quicker off the mark next time!

%hr

= render 'time_to_exchange', exchange: @exchange

app/views/exchanges/_signup.html.haml
- if logged_in?

  - if current_participant.participating?
    .row
      .six.columns
        %h2 Thanks for joining!
      .six.columns
        %p
          You are <strong>participating</strong> in this exhange. To change your mind, just use the button below.
          You can do this any time before the matching date.
        %p= button_to 'Leave the Exchange!', [@exchange, current_participant], method: :patch, params: { participant: { participating: false }}
  - else
    .row
      .six.columns
        %h2 Get involved!
      .six.columns
        %p
          You are <strong>not participating</strong> in this exchange. To change your mind and join the fun, click the button below.
          You can do this any time before the matching date.
        %p= button_to 'Join the Exchange!', [@exchange, current_participant], method: :patch, params: { participant: { participating: true }}

- else
  .row
    .ten.columns.offset-by-one
      %h2 Register your interest in this exchange:

  - if params[:invited]
    .row
      .ten.columns.offset-by-one
        %p
          Thanks! We've sent an email to <strong>#{@participant.email_address}</strong> which contains a link that you
          must click on in order to confirm your participation.
  - else
    = form_for [@exchange, @participant], data: { remote: true }, html: { class: "js-data-form" } do |f|
      .row
        .ten.columns.offset-by-one.js-data-form--errors
      .row
        .five.columns.offset-by-one= f.text_field :name, placeholder: "Name", class: 'u-full-width'
        .five.columns= f.email_field :email_address, placeholder: "E-Mail Address", class: 'u-full-width'
      .row
        .ten.columns.offset-by-one
          = f.submit 'Join the Fun!', class: 'u-pull-right button-primary'
          %p
            Signups are open until matches are made at #{@exchange.match_at.to_s(:long)} (#{current_tz_info})
          %p
            After entering your details you'll receive an email which you should use to confirm your participation. You may
            withdraw your participation any time before the matching date.

%hr

= render 'time_to_matching', exchange: @exchange

%hr

= render 'time_to_exchange', exchange: @exchange

app/views/exchanges/_time_to_exchange.html.haml
.row
  .six.columns
    %h2 Time until gifting:
  .six.columns
    %h3= countdown_timer exchange.exchange_at
    %p
      %em
        = exchange.exchange_at.to_s(:long)
        (#{current_tz_info})

app/views/exchanges/_time_to_matching.html.haml
.row
  .six.columns
    %h2 Time until matching:
  .six.columns
    %h3= countdown_timer exchange.match_at
    %p
      %em
        = exchange.match_at.to_s(:long)
        (#{current_tz_info})

app/views/exchanges/_times_form.html.haml
.row
  .five.columns.offset-by-one
    = label_tag :match_at_date, "Match participants at"
    = datepicker_field('exchange', 'match_at', f.object.match_at)
  .five.columns
    = label_tag :exchange_at_date, "Exchange gifts at"
    = datepicker_field('exchange', 'exchange_at', f.object.exchange_at)

.row
  .ten.columns.offset-by-one
    = f.time_zone_select :time_zone, nil, { default: 'London' }, class: 'u-full-width'

app/views/exchanges/edit.html.haml
- title "Update your gift exchange"

.row
  .ten.columns.offset-by-one
    %h1 Update your gift exchange

= form_for @exchange do |f|
  .row
    .ten.columns.offset-by-one
      = errors_for(f.object)

  .row
    .ten.columns.offset-by-one
      = f.label :title, "Exchange name"
      = f.text_field :title, placeholder: "Exchange name", class: 'u-full-width'

  = render 'times_form', f: f

  .row
    .ten.columns.offset-by-one
      = f.submit "Update exchange", class: 'button-primary u-pull-right'

.row
  .ten.columns.offset-by-one
    %hr

.row
  .ten.columns.offset-by-one
    - unless @exchange.participants.participating.empty?
      %h4 Confirmed Participants:
      = render 'participants/list', participants: @exchange.participants.participating, show_remove: @exchange.signup_stage?

    - unless @exchange.participants.unconfirmed.empty?
      %h4 Unconfirmed Participants:
      = render 'participants/list', participants: @exchange.participants.unconfirmed, show_remove: @exchange.signup_stage?

    - unless @exchange.participants.not_participating.empty?
      %h4 Not Participating Participants:
      = render 'participants/list', participants: @exchange.participants.not_participating, show_remove: @exchange.signup_stage?

app/views/exchanges/new.html.haml
- title "New Gift Exchange"

.row
  .ten.columns.offset-by-one
    %h1 Start your own gift exchange!

.row
  .ten.columns.offset-by-one
    %p
      To start an exchange just enter your details below. You'll receive an email to confirm your participation.
      You'll be given a URL you can share with your friends and family so that they can signup to your exchange.

= form_for @exchange do |f|
  .row
    .ten.columns.offset-by-one
      = errors_for(f.object)

  .row
    .ten.columns.offset-by-one= f.text_field :title, placeholder: "Exchange name", class: 'u-full-width'

  = f.fields_for @first_participant do |g|
    .row
      .five.columns.offset-by-one= g.text_field :name, placeholder: 'Your name', class: 'u-full-width'
      .five.columns= g.email_field :email_address, placeholder: 'Your e-mail address', class: 'u-full-width'

  .row
    .ten.columns.offset-by-one
      %hr

  = render 'times_form', f: f

  .row
    .ten.columns.offset-by-one
      = f.submit "Start the fun!", class: "button-primary u-pull-right"
      %p
        After signing up you'll receive an email which contains a link to your exchange. Use this link to administer your exchange.

app/views/exchanges/show.html.haml
- title @exchange.title

- meta 'og:url', exchange_url(@exchange)
- meta 'og:title', title
- meta 'og:description', "Join the #{@exchange.title} gift exchange on elfk.it"

.row
  .twelve.columns
    %h1= @exchange.title

.row
  .six.columns
    %h4 Share this URL with your friends and colleagues:

  .six.columns
    %h2= link_to "#{request.domain}#{exchange_path(@exchange)}", exchange_url(@exchange)

%hr

= render @exchange.stage, exchange: @exchange

%hr

.row
  .six.columns
    %h2 Participants:
  .six.columns
    - if @participants.empty?
      %h5 No confirmed participants yet, be the first!
    - else
      = render 'participants/list', participants: @participants

- if logged_in? && current_participant.admin?
  %hr
  .row
    .six.columns
      %h2 Update exchange:
    .six.columns
      %p
        As the creator of this exchange you can update the properties of this exchange, or cancel it altogether.
      %p
        = link_to "Update exchange", edit_exchange_path(@exchange), class: 'button'
        = link_to "Cancel exchange", exchange_path(@exchange), data: { confirm: "Are you sure you wish to cancel this exchange? This cannot be undone.", method: :delete }, class: 'button'